### ISSUE TITLE
KeyError: 'doc'

### ISSUE THREAD

**Issue by Z-HongWei** [lwm98/health160#48]
感觉是这个地址变更了，我尝试去抓包并更改了接口地址，尝试了多次，但均未成功，希望作者给予支援呀~~
#这个是作者的源码，我打印出了返回的数据
url = "https://www.91160.com/dep/getschmast/uid-{}/depid-{}/date-{}/p-0.html".format(
        unit_id, dep_id, now_date)
    r = session.get(url, headers=get_headers())
    print(r.text)
#这个是返回的数据以及错误，{"status":403,"msg":"#1:no access"}
{"status":403,"msg":"#1:no access"}
Traceback (most recent call last):
  File "main.py", line 630, in <module>
    run()
  File "main.py", line 587, in run
    init_data()
  File "main.py", line 579, in init_data
    set_department_configs()
  File "main.py", line 477, in set_department_configs
    doctors = r.json()["doc"]
KeyError: 'doc'
[抓到的类似的数据]：
![image](https://user-images.githubusercontent.com/47845109/171770569-4cc3e7a4-b72a-4804-b024-04464ec8c1e1.png)
[对应数据的接口]：
![image](https://user-images.githubusercontent.com/47845109/171770613-e3cb616d-7d2d-47ac-a395-62f8ace6194d.png)
[这个接口返回的数据有代码中需要的‘doc’,是一串非常长的数据]：
![image](https://user-images.githubusercontent.com/47845109/171770642-3258cc77-75dd-4fa4-acfa-69beeeded8a3.png)

**Comment by winniecjy** [comment]
我改了这里已经跑通了：   
```python
def set_doctor_configs():
    now_date = datetime.date.today().strftime("%Y-%m-%d")
    unit_id = configs["unit_id"]
    dep_id = configs["dep_id"]
    # 改用这个接口 user_key 存储在cookie中
    user_key = configs["user_key"]
    url = "https://gate.91160.com/guahao/v1/pc/sch/dep?unit_id={}&dep_id={}&date={}&p=0&user_key={}".format(
        unit_id, dep_id, now_date, user_key)
    r = session.get(url, headers=get_headers())
    doctors = r.json()["data"]["doc"]
    doc_id_arr = []
    doc_name = {}
    if configs["doc_id"] == "":
        print("=====请选择医生=====\n")
        for doctor in doctors:
            doc_id_arr.append(doctor["doctor_id"])
            doc_name[doctor["doctor_id"]] = doctor["doctor_name"]
            print("{}. {}".format(doctor["doctor_id"], doctor["doctor_name"]))
        print()
        while True:
            doctor_index = input("请输入医生编号: ")
            is_number = True if re.match(r'^\d+$', doctor_index) else False
            if is_number and int(doctor_index) in doc_id_arr:
                configs["doc_id"] = doctor_index
                configs["doctor_name"] = doc_name[int(doctor_index)]
                break
            else:
                print("输入有误，请重新输入！")
    else:
        print("当前选择医生为：%s（%s）" % (configs["doctor_name"], configs["doc_id"]))
```    
获取`user_key`的方法，我是在登录的方法里找了个位置放：   
```python
def getUserKey() -> bool:
    html = session.get("https://www.91160.com", headers=get_headers())
    cookies = requests.utils.dict_from_cookiejar(session.cookies)
    if cookies['access_hash']:
        configs['user_key'] = cookies['access_hash']
        return True
    else:
        configs['user_key'] = ''
        return False
```    
`getUserKey`随便放在了这里：    
```python   
def login(username, password) -> bool:
   #....
    if res.status_code == 200:
        r = session.post(url, data=data, headers=get_headers(), allow_redirects=False)
        if r.status_code == 302:
            redirect_url = r.headers["location"]
            logging.error(redirect_url)
            if realLogin(redirect_url):
                # 随便找了个位置取cookie
                getUserKey()
                logging.error("登录成功")
                return testLoginInfo()
                # return True
            else:
                return False
        else:
            logging.error("登录失败: {}".format(check_user(data)))
            return False
    else:
        return False
```   
btw这个函数也需要更新一下：    
```python
def brush_ticket_new(doc_id, dep_id, weeks, days) -> list:
    now_date = datetime.date.today().strftime("%Y-%m-%d")
    user_key = configs['user_key']
    unit_id = configs['unit_id']
    dep_id = configs['dep_id']
    url = "https://gate.91160.com/guahao/v1/pc/sch/doctor?user_key={}&docid={}&doc_id={}&unit_id={}&dep_id={}&date={}&days={}".format(
        user_key, doc_id, doc_id, unit_id, dep_id, now_date, 6)
    r = session.get(url, headers=get_headers())
    json_obj = r.json()
    # etc...
```

**Comment by Z-HongWei** [comment]
谢谢大佬，我尝试了一下~
成功了，真的太感谢大佬了，第三针迟迟抢不到，要崩溃了
