### ISSUE TITLE
请问一下有没有人知道下面的这个是什么问题吖，感激不尽

### ISSUE THREAD

**Issue by whitesay** [lwm98/health160#49]
请输入科室序号: 200217217
=====请选择医生=====

Traceback (most recent call last):
  File "d:\Stud\health160-main\main.py", line 598, in <module>
    run()
  File "d:\Stud\health160-main\main.py", line 555, in run
    init_data()
  File "d:\Stud\health160-main\main.py", line 548, in init_data
    set_doctor_configs()
  File "d:\Stud\health160-main\main.py", line 483, in set_doctor_configs
    doc_id_arr.append(doctor["doctor_id"])
TypeError: string indices must be integers

**Comment by wdbb123** [comment]
+1

**Comment by W200111** [comment]
+1

**Comment by yusongH** [comment]
有解决方案了吗？ @whitesay

**Comment by NewComer00** [comment]
#51

**Comment by whitesay** [comment]
已收到您的信件！

**Comment by whitesay** [comment]
已收到您的信件！
